@host=http://localhost:9880
### logger.html
{{host}}/log?type=props&key=logger
### loggers
{{host}}/log?type=loggers&appName=logserver
### light-search
{{host}}/log?type=page&search=123456789
### alidns
{{host}}/log?type=alidns&recordId=4012091293697024
X-Request-Token: xlongwei